import { packagedSkillDir } from '../paths.js'
import {
	readAlwaysInScope,
	readHeuristics,
	readIndexFiles,
	type Heuristic,
	type Rule,
} from '../heuristics.js'

export interface RubricOptions {
	version: string
	/** File stems, rule prefixes, or full rule ids. Empty means every rule. */
	only?: string[]
	format?: string
}

const FORMATS = ['markdown', 'json', 'ids']

function matches(rule: Rule, only: string[]): boolean {
	return only.some(
		(term) => term === rule.file || rule.id === term || rule.id.startsWith(term),
	)
}

/**
 * Base files are in every rubric. Beyond them, whole files when they match,
 * and single rules when the term is an id.
 */
function scope(heuristics: Heuristic[], base: string[], only: string[]): Heuristic[] {
	if (only.length === 0) {
		return heuristics
	}

	return heuristics
		.map((heuristic) => ({
			...heuristic,
			rules: base.includes(heuristic.file)
				? heuristic.rules
				: heuristic.rules.filter((rule) => matches(rule, only)),
		}))
		.filter((heuristic) => heuristic.rules.length > 0)
}

function row(rule: Rule, source?: string): string {
	const flags = [
		rule.always ? 'always' : '',
		rule.evidence === 'device' ? 'device' : '',
		source ? `from ${source}` : '',
	]
		.filter(Boolean)
		.join(', ')
	const head = `- \`${rule.id}\` (score: _, evidence: _)${flags ? ` [${flags}]` : ''}`
	const criterion = rule.check || `no Check line in the file, judge it against "${rule.title}"`
	return `${head}\n  ${criterion}`
}

function markdown(
	all: Heuristic[],
	scoped: Heuristic[],
	base: string[],
	version: string,
): string {
	const total = all.reduce((count, heuristic) => count + heuristic.rules.length, 0)
	const inScope = scoped.reduce((count, heuristic) => count + heuristic.rules.length, 0)
	const emitted = new Set(scoped.flatMap((heuristic) => heuristic.rules.map((rule) => rule.id)))

	const missing = all
		.flatMap((heuristic) => heuristic.rules.map((rule) => [heuristic, rule] as const))
		.filter(([, rule]) => rule.always && !emitted.has(rule.id))

	const extras = scoped
		.map((heuristic) => heuristic.file)
		.filter((file) => !base.includes(file))

	const out: string[] = [
		'# Review checklist',
		'',
		`Generated by trunative ${version}. ${inScope + missing.length} rules in scope, of ${total}.`,
		`Base: ${base.join(', ')}. Extra: ${extras.length > 0 ? extras.join(', ') : 'none'}.`,
		'',
		'Score each rule 1 to 5, or mark it n/a with a reason, or unrun. A row marked',
		'[device] may not be graded from the source alone. The anchors, the evidence',
		'values and what happens to the denominator are in `flow/review.md`.',
	]

	if (missing.length > 0) {
		out.push(
			'',
			'## Always in scope',
			'',
			'Scored on every run, whatever the screen is. Not available as n/a.',
			'',
			...missing.map(([heuristic, rule]) => row(rule, heuristic.path)),
		)
	}

	for (const heuristic of scoped) {
		out.push('', `## ${heuristic.file}, ${heuristic.path}`, '', ...heuristic.rules.map((rule) => row(rule)))
		if (heuristic.device) {
			out.push('', `Not from a diff: ${heuristic.device}`)
		}
	}

	return `${out.join('\n')}\n`
}

export async function rubric(options: RubricOptions): Promise<number> {
	const format = options.format ?? 'markdown'
	if (!FORMATS.includes(format)) {
		console.error(`unknown --format "${format}", expected ${FORMATS.join(', ')}`)
		return 1
	}

	const only = options.only ?? []
	const all = await readHeuristics(packagedSkillDir)
	const base = await readIndexFiles(packagedSkillDir, 'base')
	const scoped = scope(all, base, only)

	if (scoped.length === 0) {
		console.error(`no rules match --only ${only.join(', ')}`)
		return 1
	}

	if (format === 'ids') {
		for (const heuristic of scoped) {
			for (const rule of heuristic.rules) {
				console.log(rule.id)
			}
		}
		return 0
	}

	if (format === 'json') {
		console.log(
			JSON.stringify(
				{
					version: options.version,
					scope: only.length > 0 ? only : 'all',
					base,
					alwaysInScope: await readAlwaysInScope(packagedSkillDir),
					heuristics: scoped,
				},
				undefined,
				'\t',
			),
		)
		return 0
	}

	process.stdout.write(markdown(all, scoped, base, options.version))
	return 0
}
